### ISSUE TITLE
frameworks / base / services / java / com / android / server / SystemServer.java: 975: can not find symbol

### ISSUE THREAD

**Issue by moonlightly** [CarbonDev/android_frameworks_base#10]
frameworks / base / services / java / com / android / server / SystemServer.java: 975: can not find symbol
Symbol: variable TextUtils
Location: Class com.android.server.ServerThread
         if (! TextUtils.isEmpty (context.getString (

frameworks / base / services / java / com / android / server / ThemeService.java: 564: can not find symbol
Symbol: variable SYSTEMUI_NAVBAR_PKG
Location: Class android.content.res.ThemeConfig
             builder.overlay (ThemeConfig.SYSTEMUI_NAVBAR_PKG, mPkgName);

**Comment by BlueEther** [comment]
Does this need this commit as well as the others that were brought in the other day?
https://github.com/CyanogenMod/android_frameworks_base/commit/54b5fbf02d6daba0b34d6f638aaff6f65dc887c4
for   android_frameworks_base / core / java / android / content / res / ThemeConfig.java

EDIT:
this allowd build to finish, although it didn't boot - togari

**Comment by moonlightly** [comment]
this problems was fixed today,please close it .thanks
